trigger:
    batch: true
    branches:
        include:
        - main
        - develop
    paths:
        include:
        - "./Aijaz/*"

pool:
  name: 'Azure Pipelines'


variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')] #not used
  isDev: $[eq(variables['Build.SourceBranch'], 'refs/heads/develop')] #not used
  test: ""
  VMIMAGE: "windows-latest"

stages:
- template: Templates/stage_level_templates/test_build_stage_template.yml # stage template to test, build and push
  parameters:
    projectFolder: Aijaz/DDD.Prac/DDD.Prac.sln #${{variables.projectFolder}}
    buildOutputFolder: $(BUILDOUTPUTFOLDER) #${{variables.buildOutputFolder}}
    sourceFolder: $(SOURCEFOLDER) #${{variables.sourceFolder}}
    vmImageName: $(VMIMAGE)
    

- template: Templates/stage_level_templates/az_deployment_stage_template.yml # stage template for azure resource deployment to Develop
  parameters:
    vmImageName : $(VMIMAGE)
    azureSubscription : "DawoodAssesment"
    resourceGroup : "Assessment_Dawood"
    bicepFilePath : "Aijaz/DDD.Prac/DDD.Prac.AzureDeployment/azuredeploy.bicep"
    parameterFilePath : "Aijaz/DDD.Prac/DDD.Prac.AzureDeployment/azuredeploy.parameters.dev.json"
    jobName : "resourcedeployment"
    jobDescription : "deployemnt of resources"
    scriptType : "bash"
    environment: 'dev'
    deploy: true

- template: Templates/stage_level_templates/app_deployment_stage_template.yml #stage template for application deployment
  parameters:
    serviceConnection: 'DawoodAssesment'
    subscriptionId: '04f97656-0abc-4052-bd6e-eab5cd53b9f0'
    environment: 'dev'
    appType: 'webApp'